language: php
install: true
script: true
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.xn--grgoi-csa.re
  acl: public_read
  on:
    repo: chisNaN/xn--grgoi-csa.re
  region: us-west-2
notifications:
  email:
    on_failure: always
