language: ruby
install:
  -
before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: xn--grgoi-csa.re
  acl: public_read
  on:
    repo: agreg0ire/xn--grgoi-csa.re
  region: us-west-2
  endpoint: xn--grgoi-csa.re.s3-website-us-west-2.amazonaws.com
notifications:
  email:
    on_failure: always
